### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/jules_vernes_books#17]
- [ ] Add image and sound credit to itch page. Player of the first level!
- [x] Add background music.
- [ ] (Start menu, op zich is het wel aanvaardbaar nu.)
- [ ] Finish itch page with description
- [ ]  **Add end game message after last game**
- [ ] Remove exit button?
- [ ] Create screen shot for itch page.
- [ ] Export it and upload final version!
